// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Models.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201027182726_AddedJoggingSeedData")]
    partial class AddedJoggingSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Models.IdentityModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "7d56a2a5-541e-44bd-9340-a435584c934f",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "d05c7eae-dfe6-425f-8a35-671d77211e9d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "78d5c290-0874-4514-a122-11ab2afb9ee6",
                            Name = "Jogger",
                            NormalizedName = "JOGGER"
                        });
                });

            modelBuilder.Entity("Models.IdentityModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f0dadac-1e98-42f6-945a-adbf87a7af9c",
                            Email = "adminuser@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEKmbZHVb20PlkjFopZj0ukgoqnCNpyqQeOLuY8znWyi3t1OsdThACjP5l7IZ+Dd8yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "adminuser"
                        },
                        new
                        {
                            Id = 2001,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0ebf158d-8d36-4b3e-81af-8806aa7b8eee",
                            Email = "manageruser@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAECxCLc8S21Rf7m+yGzRheBnhuCeMcdfHK1iLvWjHtVAVSbVndgK4g/PQAPVQh85pNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "manageruser"
                        },
                        new
                        {
                            Id = 2002,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24292476-1fcc-4be9-98fa-62723fa5a12d",
                            Email = "joggeruser@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEN4I+xkxDDQciWCEkzPElOjc5QwmhOSQ8rVVlIKAXk+QWiXnjHJiXYrG9QTG1CCrKA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "joggeruser"
                        });
                });

            modelBuilder.Entity("Models.JoggingModels.Jogging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("DistanceInMeters")
                        .HasColumnType("float");

                    b.Property<DateTime>("JoggingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("JoggingDurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<float?>("TemperatureC")
                        .HasColumnType("real");

                    b.Property<float?>("TemperatureF")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WeatherCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("humidity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Joggings");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(3562),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4029),
                            DistanceInMeters = 2000.0,
                            JoggingDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 20,
                            Location = "London",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1001,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4718),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4743),
                            DistanceInMeters = 3000.0,
                            JoggingDate = new DateTime(2020, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 25,
                            Location = "Philadelphia",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1002,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4757),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4760),
                            DistanceInMeters = 3500.0,
                            JoggingDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 40,
                            Location = "Tashkent",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1003,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4765),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4768),
                            DistanceInMeters = 6000.0,
                            JoggingDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 60,
                            Location = "London",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1004,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4772),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4775),
                            DistanceInMeters = 800.0,
                            JoggingDate = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 10,
                            Location = "London",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1005,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4780),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4783),
                            DistanceInMeters = 5300.0,
                            JoggingDate = new DateTime(2020, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 50,
                            Location = "London",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1006,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4787),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4790),
                            DistanceInMeters = 7000.0,
                            JoggingDate = new DateTime(2020, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 80,
                            Location = "London",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1007,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4795),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4798),
                            DistanceInMeters = 500.0,
                            JoggingDate = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 10,
                            Location = "London",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        },
                        new
                        {
                            Id = 1008,
                            DateCreated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4802),
                            DateUpdated = new DateTime(2020, 10, 27, 14, 27, 26, 341, DateTimeKind.Local).AddTicks(4805),
                            DistanceInMeters = 10000.0,
                            JoggingDate = new DateTime(2020, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JoggingDurationInMinutes = 120,
                            Location = "London",
                            TemperatureC = 20f,
                            TemperatureF = 60f,
                            UserId = 2002,
                            WeatherCondition = "Clear",
                            humidity = 30f
                        });
                });

            modelBuilder.Entity("Models.IdentityModels.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<int>");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 2000,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2001,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2002,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Models.IdentityModels.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Models.IdentityModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Models.IdentityModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Models.IdentityModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.JoggingModels.Jogging", b =>
                {
                    b.HasOne("Models.IdentityModels.User", "User")
                        .WithMany("Joggings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.IdentityModels.UserRole", b =>
                {
                    b.HasOne("Models.IdentityModels.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.IdentityModels.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
